apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-tracker-qa

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: task-tracker-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

  - target:
      kind: Deployment
      name: task-tracker-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: HorizontalPodAutoscaler
      name: task-tracker-backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

  - target:
      kind: Ingress
      name: task-tracker-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: qa-app.rashmidevops.xyz
      - op: replace
        path: /spec/rules/1/host
        value: qa-api.rashmidevops.xyz

configMapGenerator:
  - name: task-tracker-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - RATE_LIMIT_MAX=300
      - DB_NAME=tasktracker_qa
      - ALLOWED_ORIGINS=https://qa-app.rashmidevops.xyz

images:
  - name: DOCKER_REGISTRY/task-tracker-backend
    newName: 897074277336.dkr.ecr.us-east-1.amazonaws.com/task-tracker-backend
    newTag: qa-latest
  - name: DOCKER_REGISTRY/task-tracker-frontend
    newName: 897074277336.dkr.ecr.us-east-1.amazonaws.com/task-tracker-frontend
    newTag: qa-latest
